### ISSUE TITLE
Problem on Ubuntu 20.10

### ISSUE THREAD

**Issue by gtoscano** [chrisspiegl/ControlThemAll#2]
Hi Chris, you've done a tremendous work. Thank you!

I am trying to run ControlThemAll on Ubuntu 20.10, pnpm version 6.24.2, npm@6.14.8. However, I get the following error:

> controlthemall@0.0.1 start /home/gtoscano/Dropbox/Files/Code/projects/streaming/ControlThemAll
> node .

(node:4161206) ExperimentalWarning: The ESM module loader is experimental.
file:///home/gtoscano/Dropbox/Files/Code/projects/streaming/ControlThemAll/index.js:610
    return _.map(_.filter(this.config.buttons, (el) => el.action === action || el.noteOn?.action == action || el.noteOff?.action == action), (el) => el.note)
                                                                                         ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:88:18)
    at async link (internal/modules/esm/module_job.js:41:21)
 ELIFECYCLE  Command failed with exit code 1.

**Comment by chrisspiegl** [comment]
Hi @gtoscano, can you let me know which version of node.js you are using?
I am running node version `16.13.0` and it works as expected.
